package com.example.Attendence.model;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

@Document(collection = "OfficeDayCal")
public class OfficeDayCal {
    @Id
    private String id; // Assuming you want an autogenerated ID for the entity

     String month;
     String year;
     String Status;
     String entryDate;
    public OfficeDayCal() {
    }
    public OfficeDayCal(String month, String year,String entryDate, String status) {
        this.month = month;
        this.year = year;
        this.entryDate = entryDate;
        Status = status;
    }

    public String getId() {
        return id;
    }
    public void setId(String id) {
        this.id = id;
    }
    public String getMonth() {
        return month;
    }
    public void setMonth(String month) {
        this.month = month;
    }
    public String getYear() {
        return year;
    }
    public void setYear(String year) {
        this.year = year;
    }
    public String getStatus() {

        return Status;
    }
    public void setStatus(String status) {
        Status = status;
    }

    public String getEntryDate() {
        return entryDate;
    }
    public void setEntryDate(String entryDate) {
        this.entryDate = entryDate;
    }

    @Override
    public String toString() {
        return "OfficeDayCal{" +
                "id='" + id + '\'' +
                ", month='" + month + '\'' +
                ", year='" + year + '\'' +
                ", Status='" + Status + '\'' +
                ", entryDate='" + entryDate + '\'' +
                '}';
    }
}
