package com.example.Attendence.model;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.LocalDate;

@Document(collection = "OfficeDayCal")
public class OfficeDayCal {
    @Id
    private String id; // Assuming you want an autogenerated ID for the entity

     String month;
     String year;
     String status;
     String date;
     LocalDate entryDate;
    public OfficeDayCal() {
    }
    public OfficeDayCal(String month, String year,String date,LocalDate entryDate, String status) {
        this.month = month;
        this.year = year;
        this.date = date;
        this.entryDate = entryDate;
        this.status = status;
    }

    public String getId() {
        return id;
    }
    public void setId(String id) {
        this.id = id;
    }
    public String getMonth() {
        return month;
    }
    public void setMonth(String month) {
        this.month = month;
    }
    public String getYear() {
        return year;
    }
    public void setYear(String year) {
        this.year = year;
    }
    public String getStatus() {

        return status;
    }
    public void setStatus(String status) {
        status = status;
    }
    public String getDate() {
        return date;
    }
    public void setDate(String date) {
        this.date = date;
    }

    public LocalDate getEntryDate() {
        return entryDate;
    }
    public void setEntryDate(LocalDate entryDate) {
        this.entryDate = entryDate;
    }

    @Override
    public String toString() {
        return "OfficeDayCal{" +
                "id='" + id + '\'' +
                ", month='" + month + '\'' +
                ", year='" + year + '\'' +
                ", status='" + status + '\'' +
                ", date='" + date + '\'' +
                ", entryDate=" + entryDate +
                '}';
    }
}
